# This script builds all the problem sets for
# Econ103. It outputs:
#
#   (1) pdfs of the problem sets: HWxx.pdf
#   (2) pdf solutions: HWxx_solutions.pdf
#   (3) R code if applicable: HWxx.R
#
# The raw source for the problem sets is 
# contained in a number of .tex and .Rnw files.
# The first few assignments are .tex since they
# don't incorporate any R code and the rest are
# .Rnw since they do.
#
# The first step is to knit all the .Rnw files
# into .tex files and, while we're at it, purl
# all the R code. The command list.files takes
# a regular expression as its second argument.
# Since I'm still a regex noob, I use glob2rx
# to convert a more familiar command line
# wildcard expression to regex
require(knitr)
match.rnw <- glob2rx("*.Rnw")
rnw.list <- list.files(".", match.rnw)
for(i in 1:length(rnw.list)){
  knit(rnw.list[i])
  purl(rnw.list[i], documentation = 0)
}
#
# The next step is compile all the .tex files 
# for the problem sets. Note that we do *not*
# want to compile the concordance.tex files
# generated by knitr, so we list the files as
# folows:
match.HWxx <- glob2rx("HW??.tex")
HWxx.list <- list.files(".", match.HWxx)
#
# Now we need to compile each of the files
# in HWxx.list *twice* -- once to create a 
# pdf of the problem set without solutions
# and another with solutions. To make this
# simpler, all the raw .tex and .Rnw files
# for the problem sets accept a command line
# argument. The .tex files that emerge from
# knitr inherit this argument as wel.
# Running:
#
#   pdflatex "\def\showanswers{1} \input{HWxx.tex}"
#
# tells pdflatex to compile the document with
# "\printanswers" while running 
#   
#   pdflatex HWxx.tex
#
# tells pdflatex to compile with "\noprintanswers."
#
# We'll start by compiling without answers:
noanswers <- paste0("pdflatex ", HWxx.list)
