# This script builds all the problem sets for
# Econ103. It outputs:
#
#   (1) pdfs of the problem sets: HWxx.pdf
#   (2) pdf solutions: HWxx_solutions.pdf
#   (3) R code if applicable: HWxx.R
#
# The raw source for the problem sets is 
# contained in a number of .tex and .Rnw files.
# The first few assignments are .tex since they
# don't incorporate any R code and the rest are
# .Rnw since they do.
#
# The first step is to knit all the .Rnw files
# into .tex files and, while we're at it, purl
# all the R code. The command list.files takes
# a regular expression as its second argument.
# Since I'm still a regex noob, I use glob2rx
# to convert a more familiar command line
# wildcard expression to regex
require(knitr)
match.rnw <- glob2rx("*.Rnw")
rnw.list <- list.files(".", match.rnw)
for(i in 1:length(rnw.list)){
  knit(rnw.list[i])
  purl(rnw.list[i], documentation = 0)
}
rm(list = ls())
#
# The next step is compile all the .tex files 
# for the problem sets. Note that we do *not*
# want to compile the concordance.tex files
# generated by knitr, so we list the files as
# folows:
match.HWxx <- glob2rx("HW??.tex")
HWxx.list <- list.files(".", match.HWxx)
#
# Now we need to compile each of the files
# in HWxx.list *twice* -- once to create a 
# pdf of the problem set without solutions
# and another with solutions. To make this
# simpler, all the raw .tex and .Rnw files
# for the problem sets accept a command line
# argument. The .tex files that emerge from
# knitr inherit this argument as wel.
# Running:
#
#   pdflatex "\def\showanswers{1} \input{HWxx.tex}"
#
# tells pdflatex to compile the document with
# "\printanswers" while running 
#   
#   pdflatex HWxx.tex
#
# tells pdflatex to compile with "\noprintanswers."
#
# We'll start by compiling without answers:
noanswers <- paste0("pdflatex ", HWxx.list)
for(i in 1:length(noanswers)){
  #Run twice to the LaTex counters etc. are correct
  system(noanswers[i])
  system(noanswers[i])
}
#
# To compile with answers, the commands are 
# more complicated. First, we need to pass the
# appropriate command line argument so that
# we get "\printanswers." Second, we want to
# specify the name of the *output file* so that
# it takes the form HWxx_solutions.pdf. We'll
# build up the commands in steps:
#
# Step 1: generate output file names
out.names <- paste0(sapply(strsplit(HWxx.list, split = ".", fixed = TRUE), function(x) x[1]), "_solutions")
#
# Step 2: build up all of the commands
commands <- rep(NA, length(out.names))
for (i in 1:length(out.names)){
  # Double quotes inside single quotes are 
  # a more readable way to escape quoted text
  arg1 <- paste0('-jobname="',  out.names[i], '"')
  arg2 <- paste0('"\\def\\showanswers{1} \\input{',  HWxx.list[i], '}"')
  command <- paste("pdflatex", arg1, arg2)
  commands[i] <- command
}
#
# Step 3: Run each command twice
for(i in 1:length(out.names)){
  system(commands[i])
  system(commands[i])
}
#
# Finally, clean up
rm(list = ls())